# CircleCI configuration
# see: https://circleci.com/docs/2.0/configuration-reference/

version: 2.1

executors:
  pajbot:
    docker:
      - image: debian:buster
    working_directory: ~/pajbot

commands:
  create_setup:
    steps:
      - run:
          name: Update apt database
          command: apt-get update
      - run:
          name: Install python and dependencies for python packages
          command: apt-get install git python3 python3-pip python3-venv libssl-dev -y
      - checkout
      - restore_cache:
          name: Restore cached virtual environment
          key: v1-requirements-prod@{{ checksum "requirements.txt" }}-dev@{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install virtual environment and dependencies
          command: ./install/venvinstall.sh --dev
      - save_cache:
          name: Save virtual environment to cache
          key: v1-requirements-prod@{{ checksum "requirements.txt" }}-dev@{{ checksum "requirements-dev.txt" }}
          paths:
            - ./venv

jobs:
  test:
    executor: pajbot
    steps:
      - create_setup
      - run:
          name: Run tests
          command: ./venv/bin/pytest
  lint:
    executor: pajbot
    steps:
      - create_setup
      - run:
          name: Run flake8 (lint)
          command: ./venv/bin/flake8
  check_format:
    executor: pajbot
    steps:
      - create_setup
      - run:
          name: Run black in check mode
          command: ./venv/bin/black --check --diff pajbot alembic scripts

# add one workflow that runs all jobs in parallel
workflows:
  version: 2
  build:
    jobs:
      - test
      - lint
      - check_format
